#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands
{
    SYSTEM_COMMAND0_SUM,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_EXIT,
    SYSTEM_COMMAND10_SLEEP, 
    SYSTEM_COMMAND11_WAKE,
    SYSTEM_COMMAND12_GET_TICKS,
    SYSTEM_COMMAND13_PUT_PIXEL,
    null,
    SYSTEM_COMMAND15_DRAW_RECT,
    SYSTEM_COMMAND16_DRAW_HLINE,
    SYSTEM_COMMAND17_DRAW_VLINE,
    SYSTEM_COMMAND18_DRAW_GRID
};

void isr80h_register_commands();

#endif